name: build and deploy for fast-writing
on: [push]
  # paths:
  #   - 'apps/fast-writing-api/**'
  #   - 'pkg/pb/**'
env:
  PROJECT_ID: anan-project
  PRODUCT_NAME: fast-writing
  FAST_WRITING_API_SERVICE_NAME: fast-writing-api
jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Setup gcloud CLI
      - uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: projects/474794270878/locations/global/workloadIdentityPools/gh-pools/providers/gh-provider
          service_account: github-actions@anan-project.iam.gserviceaccount.com

      # Build docker image
      - name: Set Env
        run: echo "tag=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - name: Build Image for Fast Writing
        run: |-
          docker build -t asia-northeast1-docker.pkg.dev/$PROJECT_ID/$PRODUCT_NAME/$FAST_WRITING_API_SERVICE_NAME:$tag -f apps/$FAST_WRITING_API_SERVICE_NAME/Dockerfile .
      # Configure docker to use the gcloud command-line tool as a credential helper
      - run: |
          gcloud auth configure-docker asia-northeast1-docker.pkg.dev
      # Push image to Google Container Registry
      - name: Push Writing API
        run: |-
          docker push asia-northeast1-docker.pkg.dev/$PROJECT_ID/$PRODUCT_NAME/$FAST_WRITING_API_SERVICE_NAME:$tag

  deploy:
    needs: [build]
    name: Cloud Run Deploy
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Setup gcloud CLI
      - uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: projects/474794270878/locations/global/workloadIdentityPools/gh-pools/providers/gh-provider
          service_account: github-actions@anan-project.iam.gserviceaccount.com

      - name: Set Env
        run: echo "tag=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      # - name: Update Secret
      #   run: echo "test3" | gcloud secrets versions add $SAMPLE_SECRET_NAME --data-file=-

      - name: Deploy Writing API
        run: |-
          gcloud run deploy $FAST_WRITING_API_SERVICE_NAME \
            --image asia-northeast1-docker.pkg.dev/$PROJECT_ID/$PRODUCT_NAME/$FAST_WRITING_API_SERVICE_NAME:$tag \
            --project $PROJECT_ID \
            --platform managed --region asia-northeast1
