application:
  port: 10001

database:
  type: "local"
  host: "127.0.0.1"
  port: 3306
  user: "system"
  password: "system"
  schema: "fast_writing"
  timeout: 5
  debug: true

search-api:
  host: "127.0.0.1"
  port: "10002"
