application:
  port: 10001
  onCloud: false

search:
  host: "127.0.0.1"
  port: 10002
  ssl: false
  token: false

database:
  type: "local"
  host: "127.0.0.1"
  port: 3306
  user: "system"
  password: "system"
  schema: "fast_writing"
  timeout: 5
  debug: true
