// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: proto/fast-writing.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserServiceClient interface {
	GetUser(ctx context.Context, in *UserId, opts ...grpc.CallOption) (*User, error)
}

type userServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserServiceClient(cc grpc.ClientConnInterface) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) GetUser(ctx context.Context, in *UserId, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/fastwriting.UserService/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
// All implementations should embed UnimplementedUserServiceServer
// for forward compatibility
type UserServiceServer interface {
	GetUser(context.Context, *UserId) (*User, error)
}

// UnimplementedUserServiceServer should be embedded to have forward compatible implementations.
type UnimplementedUserServiceServer struct {
}

func (UnimplementedUserServiceServer) GetUser(context.Context, *UserId) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}

// UnsafeUserServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserServiceServer will
// result in compilation errors.
type UnsafeUserServiceServer interface {
	mustEmbedUnimplementedUserServiceServer()
}

func RegisterUserServiceServer(s grpc.ServiceRegistrar, srv UserServiceServer) {
	s.RegisterService(&UserService_ServiceDesc, srv)
}

func _UserService_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fastwriting.UserService/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUser(ctx, req.(*UserId))
	}
	return interceptor(ctx, in, info, handler)
}

// UserService_ServiceDesc is the grpc.ServiceDesc for UserService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fastwriting.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUser",
			Handler:    _UserService_GetUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/fast-writing.proto",
}

// WritingServiceClient is the client API for WritingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WritingServiceClient interface {
	GetContents(ctx context.Context, in *ContentsId, opts ...grpc.CallOption) (*Contents, error)
	GetContentsList(ctx context.Context, in *ContentsQueryParams, opts ...grpc.CallOption) (*ContentsList, error)
	GetUserContentsList(ctx context.Context, in *UserContentsQueryParams, opts ...grpc.CallOption) (*ContentsList, error)
}

type writingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWritingServiceClient(cc grpc.ClientConnInterface) WritingServiceClient {
	return &writingServiceClient{cc}
}

func (c *writingServiceClient) GetContents(ctx context.Context, in *ContentsId, opts ...grpc.CallOption) (*Contents, error) {
	out := new(Contents)
	err := c.cc.Invoke(ctx, "/fastwriting.WritingService/GetContents", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *writingServiceClient) GetContentsList(ctx context.Context, in *ContentsQueryParams, opts ...grpc.CallOption) (*ContentsList, error) {
	out := new(ContentsList)
	err := c.cc.Invoke(ctx, "/fastwriting.WritingService/GetContentsList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *writingServiceClient) GetUserContentsList(ctx context.Context, in *UserContentsQueryParams, opts ...grpc.CallOption) (*ContentsList, error) {
	out := new(ContentsList)
	err := c.cc.Invoke(ctx, "/fastwriting.WritingService/GetUserContentsList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WritingServiceServer is the server API for WritingService service.
// All implementations should embed UnimplementedWritingServiceServer
// for forward compatibility
type WritingServiceServer interface {
	GetContents(context.Context, *ContentsId) (*Contents, error)
	GetContentsList(context.Context, *ContentsQueryParams) (*ContentsList, error)
	GetUserContentsList(context.Context, *UserContentsQueryParams) (*ContentsList, error)
}

// UnimplementedWritingServiceServer should be embedded to have forward compatible implementations.
type UnimplementedWritingServiceServer struct {
}

func (UnimplementedWritingServiceServer) GetContents(context.Context, *ContentsId) (*Contents, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetContents not implemented")
}
func (UnimplementedWritingServiceServer) GetContentsList(context.Context, *ContentsQueryParams) (*ContentsList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetContentsList not implemented")
}
func (UnimplementedWritingServiceServer) GetUserContentsList(context.Context, *UserContentsQueryParams) (*ContentsList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserContentsList not implemented")
}

// UnsafeWritingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WritingServiceServer will
// result in compilation errors.
type UnsafeWritingServiceServer interface {
	mustEmbedUnimplementedWritingServiceServer()
}

func RegisterWritingServiceServer(s grpc.ServiceRegistrar, srv WritingServiceServer) {
	s.RegisterService(&WritingService_ServiceDesc, srv)
}

func _WritingService_GetContents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContentsId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WritingServiceServer).GetContents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fastwriting.WritingService/GetContents",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WritingServiceServer).GetContents(ctx, req.(*ContentsId))
	}
	return interceptor(ctx, in, info, handler)
}

func _WritingService_GetContentsList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContentsQueryParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WritingServiceServer).GetContentsList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fastwriting.WritingService/GetContentsList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WritingServiceServer).GetContentsList(ctx, req.(*ContentsQueryParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _WritingService_GetUserContentsList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserContentsQueryParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WritingServiceServer).GetUserContentsList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fastwriting.WritingService/GetUserContentsList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WritingServiceServer).GetUserContentsList(ctx, req.(*UserContentsQueryParams))
	}
	return interceptor(ctx, in, info, handler)
}

// WritingService_ServiceDesc is the grpc.ServiceDesc for WritingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WritingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fastwriting.WritingService",
	HandlerType: (*WritingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetContents",
			Handler:    _WritingService_GetContents_Handler,
		},
		{
			MethodName: "GetContentsList",
			Handler:    _WritingService_GetContentsList_Handler,
		},
		{
			MethodName: "GetUserContentsList",
			Handler:    _WritingService_GetUserContentsList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/fast-writing.proto",
}
