// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.4
// source: models/query.proto

package models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueryParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Limit  int32 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset int32 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
}

func (x *QueryParams) Reset() {
	*x = QueryParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_models_query_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryParams) ProtoMessage() {}

func (x *QueryParams) ProtoReflect() protoreflect.Message {
	mi := &file_models_query_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryParams.ProtoReflect.Descriptor instead.
func (*QueryParams) Descriptor() ([]byte, []int) {
	return file_models_query_proto_rawDescGZIP(), []int{0}
}

func (x *QueryParams) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *QueryParams) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ContentsQueryParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Params *QueryParams `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
}

func (x *ContentsQueryParams) Reset() {
	*x = ContentsQueryParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_models_query_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContentsQueryParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentsQueryParams) ProtoMessage() {}

func (x *ContentsQueryParams) ProtoReflect() protoreflect.Message {
	mi := &file_models_query_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentsQueryParams.ProtoReflect.Descriptor instead.
func (*ContentsQueryParams) Descriptor() ([]byte, []int) {
	return file_models_query_proto_rawDescGZIP(), []int{1}
}

func (x *ContentsQueryParams) GetParams() *QueryParams {
	if x != nil {
		return x.Params
	}
	return nil
}

type UserContentsQueryParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Params *QueryParams `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	Id     *UserId      `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *UserContentsQueryParams) Reset() {
	*x = UserContentsQueryParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_models_query_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserContentsQueryParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserContentsQueryParams) ProtoMessage() {}

func (x *UserContentsQueryParams) ProtoReflect() protoreflect.Message {
	mi := &file_models_query_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserContentsQueryParams.ProtoReflect.Descriptor instead.
func (*UserContentsQueryParams) Descriptor() ([]byte, []int) {
	return file_models_query_proto_rawDescGZIP(), []int{2}
}

func (x *UserContentsQueryParams) GetParams() *QueryParams {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *UserContentsQueryParams) GetId() *UserId {
	if x != nil {
		return x.Id
	}
	return nil
}

type TitleQueryParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Params *QueryParams `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	Title  string       `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
}

func (x *TitleQueryParams) Reset() {
	*x = TitleQueryParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_models_query_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TitleQueryParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TitleQueryParams) ProtoMessage() {}

func (x *TitleQueryParams) ProtoReflect() protoreflect.Message {
	mi := &file_models_query_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TitleQueryParams.ProtoReflect.Descriptor instead.
func (*TitleQueryParams) Descriptor() ([]byte, []int) {
	return file_models_query_proto_rawDescGZIP(), []int{3}
}

func (x *TitleQueryParams) GetParams() *QueryParams {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *TitleQueryParams) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

var File_models_query_proto protoreflect.FileDescriptor

var file_models_query_proto_rawDesc = []byte{
	0x0a, 0x12, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f, 0x71, 0x75, 0x65, 0x72, 0x79, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x1a, 0x11, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x73, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x3b, 0x0a, 0x0b, 0x51, 0x75, 0x65, 0x72, 0x79, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x14,
	0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c,
	0x69, 0x6d, 0x69, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x22, 0x42, 0x0a, 0x13,
	0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x51, 0x75, 0x65, 0x72, 0x79, 0x50, 0x61, 0x72,
	0x61, 0x6d, 0x73, 0x12, 0x2b, 0x0a, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x51, 0x75, 0x65,
	0x72, 0x79, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x52, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73,
	0x22, 0x66, 0x0a, 0x17, 0x55, 0x73, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73,
	0x51, 0x75, 0x65, 0x72, 0x79, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x2b, 0x0a, 0x06, 0x70,
	0x61, 0x72, 0x61, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x73, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73,
	0x52, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x1e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x52, 0x02, 0x69, 0x64, 0x22, 0x55, 0x0a, 0x10, 0x54, 0x69, 0x74, 0x6c,
	0x65, 0x51, 0x75, 0x65, 0x72, 0x79, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x2b, 0x0a, 0x06,
	0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6d,
	0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x50, 0x61, 0x72, 0x61, 0x6d,
	0x73, 0x52, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x42,
	0x1c, 0x5a, 0x1a, 0x66, 0x61, 0x73, 0x74, 0x2d, 0x77, 0x72, 0x69, 0x74, 0x69, 0x6e, 0x67, 0x2f,
	0x70, 0x6b, 0x67, 0x2f, 0x70, 0x62, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_models_query_proto_rawDescOnce sync.Once
	file_models_query_proto_rawDescData = file_models_query_proto_rawDesc
)

func file_models_query_proto_rawDescGZIP() []byte {
	file_models_query_proto_rawDescOnce.Do(func() {
		file_models_query_proto_rawDescData = protoimpl.X.CompressGZIP(file_models_query_proto_rawDescData)
	})
	return file_models_query_proto_rawDescData
}

var file_models_query_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_models_query_proto_goTypes = []interface{}{
	(*QueryParams)(nil),             // 0: models.QueryParams
	(*ContentsQueryParams)(nil),     // 1: models.ContentsQueryParams
	(*UserContentsQueryParams)(nil), // 2: models.UserContentsQueryParams
	(*TitleQueryParams)(nil),        // 3: models.TitleQueryParams
	(*UserId)(nil),                  // 4: models.UserId
}
var file_models_query_proto_depIdxs = []int32{
	0, // 0: models.ContentsQueryParams.params:type_name -> models.QueryParams
	0, // 1: models.UserContentsQueryParams.params:type_name -> models.QueryParams
	4, // 2: models.UserContentsQueryParams.id:type_name -> models.UserId
	0, // 3: models.TitleQueryParams.params:type_name -> models.QueryParams
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_models_query_proto_init() }
func file_models_query_proto_init() {
	if File_models_query_proto != nil {
		return
	}
	file_models_user_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_models_query_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_models_query_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContentsQueryParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_models_query_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserContentsQueryParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_models_query_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TitleQueryParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_models_query_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_models_query_proto_goTypes,
		DependencyIndexes: file_models_query_proto_depIdxs,
		MessageInfos:      file_models_query_proto_msgTypes,
	}.Build()
	File_models_query_proto = out.File
	file_models_query_proto_rawDesc = nil
	file_models_query_proto_goTypes = nil
	file_models_query_proto_depIdxs = nil
}
